var express = require('express');
var session = require('express-session')
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var cors = require('cors');
var response = require('./factories/standard-response');
var log = require('./logger');
var config = require('../config');
var jwt = require('jwt-simple');

var app = express();

app.use(cors());
app.use(logger('dev'));
app.use(bodyParser.json());
//todo add redis so session storage is not just server side
app.use(session({
  secret: 'keyboard cat',
  saveUninitialized: false,
  resave: false
}));

/**
 * decode JWT present in the query params
 * */
app.use(function(req, res, next) {
  if (req.query.jwt)
    req.auth = jwt.decode(req.query.jwt, config.jwtSecret);
  next();
});
//health check for elb
app.use('/health', function(req, res) { res.sendStatus(200); });
app.use('/facebook', require('./routes/providers/facebook'));
app.use('/twitter', require('./routes/providers/twitter'));
app.use('/oauth1', require('./routes/oauth1').router);

// catch 404 and forward to error handler
app.use(function(req, res, next) {
  response.error('invalid route requested', res, {
    status: 404,
    userMessage: 'The route specified does not exist'
  });
});

app.use(function(err, req, res, next) {
  //if the error message was generated by the system
  response.error({
      message: 'Server Thrown Error',
      thrownMsg:  err.message || err
    }, res);
});


module.exports = app;
