//3rd party modules
var app = require('express')();
var request = require('request-promise');
var session = require('express-session');
var logger = require('morgan');
var bodyParser = require('body-parser');
var cors = require('cors');
var jwt = require('jwt-simple');
//app modules
var log = require('./logger');
var config = require('../config');
var response = require('./factories/standard-response');

app.use(cors());
app.use(logger('dev'));
app.use(bodyParser.json());

//health check for elb
app.use('/health', function(req, res) { res.sendStatus(200); });
app.use('/oauth1', require('./routes/oauth1').router);
app.use('/oauth2', require('./routes/oauth2'));
/**
 * decode JWT present in the query params
 * */
app.use(function(req, res, next) {
  if (!req.query.jwt)
    return response.error('auth tokens not passed to request', res);
  req.auth = jwt.decode(req.query.jwt, config.jwtSecret);
  next();
});
app.use('/facebook', require('./routes/providers/facebook'));
app.use('/twitter', require('./routes/providers/twitter'));


// catch 404 and forward to error handler
app.use(function(req, res, next) {
  response.error('invalid route requested', res, {
    status: 404,
    userMessage: 'The route specified does not exist'
  });
});

app.use(function(err, req, res, next) {
  //if the error message was generated by the system
  response.error({
      message: 'Server Thrown Error',
      thrownMsg:  err.message || err
    }, res);
});


module.exports = app;
